CREATE TABLE IF NOT EXISTS Users (
    Id SERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS Matches (
    Id SERIAL PRIMARY KEY,
    WinnerId INT REFERENCES Users(Id),
    LoserId INT REFERENCES Users(Id),
    PlayedAt TIMESTAMP DEFAULT NOW()
);
